name: AWS

on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/test-gha-Role-Y460O0X67UE3
        aws-region: us-east-1
        role-session-name: githubci
